// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDej3v5hL1JmXDtirEGcDiaXf1CpR4ik',
    appId: '1:1087588012232:web:4e85c4582a5ff9657b95fd',
    messagingSenderId: '1087588012232',
    projectId: 'autocarcare-f5953',
    authDomain: 'autocarcare-f5953.firebaseapp.com',
    storageBucket: 'autocarcare-f5953.appspot.com',
    measurementId: 'G-WYQ2X39WPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLFh8UWS6B8BCKrGLC9djSeuD3nixHwQ',
    appId: '1:1087588012232:android:3bab759a8bd3687c7b95fd',
    messagingSenderId: '1087588012232',
    projectId: 'autocarcare-f5953',
    storageBucket: 'autocarcare-f5953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcb1ftJVpdDaD87neOXJkyPOagKTEZeQY',
    appId: '1:1087588012232:ios:0f4518b0e7197c237b95fd',
    messagingSenderId: '1087588012232',
    projectId: 'autocarcare-f5953',
    storageBucket: 'autocarcare-f5953.appspot.com',
    iosClientId: '1087588012232-ct92kdmf0lqias6esbm9g6c7h88a2o8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.autocarservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcb1ftJVpdDaD87neOXJkyPOagKTEZeQY',
    appId: '1:1087588012232:ios:0f4518b0e7197c237b95fd',
    messagingSenderId: '1087588012232',
    projectId: 'autocarcare-f5953',
    storageBucket: 'autocarcare-f5953.appspot.com',
    iosClientId: '1087588012232-ct92kdmf0lqias6esbm9g6c7h88a2o8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.autocarservice',
  );
}
